### ISSUE TITLE
pvp channels

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#102]
The default pvp channel just silently resets on death so it confuses players. Therefore:
* The default channel (`1`) should NOT reset on death because one could just cast `@pvp` while being dead. The channel should automatically reset on login even if the player did not turn it off before logging out. (suggested behavior)

OR
* The default channel (`1`) SHOULD be reset on death BUT should tell the player about it (`PvP : Off`). But this would not solve the problem of players finding it annoying to have to type `@pvp` every single time they die.

- - -
To solve a bug with the fight club,  we need to:
* If we choose to first solution for the bug described above then we should make any channel that is NOT `1` reset on death.

OR
* If we choose the second one then we make any channel reset on death.

**Comment by wushin** [comment]
Too bad it couldn't be a status icon, I guess I'm fine with either method though.
