### ISSUE TITLE
Mobs aren't properly syncing with client

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#112]
<Rawng> as you walk into an area that hasn't had players in a while, the new mobs are in incorrect locations
<Rawng> to see it walk up to a stationary mob and try to attack it

**Comment by mekolat** [comment]
@wushin #106 was supposed to fix it
...But it does not and I don't know why. Manaplus might just refuse to fix the mob position or maybe I need to spend 2 more hours on this. The pr does make it better as it makes the client set the mob direction based on the mob to_x and to_y but somehow they don't walk to that to_x and to_y. I'll have to dig deeper

**Comment by Rawng** [comment]
A good place to start would likely be to go back to before the most recent movement packet fixes and take a closer look at what was changed.

**Comment by mekolat** [comment]
move3 got reverted
