### ISSUE TITLE
Attack speeds are broken

### ISSUE THREAD

**Issue by pydsigner** [themanaworld/tmwa#127]
Problems:
- Currently it is possible to specify a weapon's base delay by setting the View to certain values, which are actually supposed to describe the weapon's type. Thus the Setzer is a "two-handed sword" and the Short Sword is a "dagger." The delays attached to the various values seem pretty arbitrary and are, at any rate, in defiance of the specified meaning.
- `bonus bAspdRate, <n>` can be used in equip scripts to modify the attack delay. However, it can only be used to increase the speed; n < 0 has no effect.

Possible solution:
Return View to its proper usage and add a Delay attribute to item_db.txt.

**Comment by mekolat** [comment]
fixing this would change gameplay (bugs used as features)
