### ISSUE TITLE
Shop NPCs

### ISSUE THREAD

**Issue by pydsigner** [themanaworld/tmwa#128]
Shop NPCs are incredibly single-focused, which makes sense since they are "shop NPCs". However, this causes an issue where nothing special can be done without constructing an ugly menu shop. Things such as requiring a certain level to open the shop or having an introductory dialog are impossible.

Possible solution: remove the "shop" NPC type and add a `shop` command similar to `menu`. This would allow much more customization without bloating code.

Example:

```
shop
    "RedDye", -1,
    @seconditem$, @secondprice;
```

**Comment by mekolat** [comment]
I love this idea

**Comment by pydsigner** [comment]
As an aside and a note on the variable insertion for the value there, it'd be nice if normal menus worked the same way; it would massively simplify that sort of dynamic menu.
