### ISSUE TITLE
move constants to script

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#175]
You should be able to write `0xFFFF` instead of `65535`

will have to be done in ast

**Comment by o11c** [comment]
This should already work in half the places, but deliberately should *not* work in savefiles.

**Comment by mekolat** [comment]
o_o last time I checked I wasn't able to use hex in tmwscript. perhaps I did something wrong

**Comment by o11c** [comment]
It works for scripts here: https://github.com/themanaworld/tmwa/blob/master/src/map/script-parse.cpp#L363

But it does not work for const.txt here: https://github.com/themanaworld/tmwa/blob/master/src/map/script-startup.cpp#L97

The tricky bit is that `strtoul` introduces a locale dependency, so *really* shouldn't be used. Whereas `extract` is used for save files and must not allow any base other than 10.

Probably the best thing to do is add an `any_base()` extractor adaptor à la `lstripping`.

**Comment by o11c** [comment]
But my long term plan was to ditch `const.txt` entirely in favor of parsing constants specially in scripts anyway (there are currently a lot of `$@` that are really constants).

**Comment by o11c** [comment]
Though note that param-type constants *cannot* be implemented directly in script yet.

**Comment by mekolat** [comment]
@o11c can't we have something like `param FOO, <id>;` ?

**Comment by o11c** [comment]
There's already `readparam` and `setparam` (though they don't accept the same set of `SP` values yet, but that can easily change), but in order to not regress execution speed, it should really be done by the bytecode (or asm in my plan - see the wiki), not by the (builtin-)function-call layer (this is also a concern with normal consts).
