### ISSUE TITLE
[DIS] Add server-side bot detection

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#187]
`Celestia` asks if it would be possible to add server-side bot detection so that GMs would be notified upon login (or using a GM command) of players with suspicious behaviour.

`[18:19] Celestia's Luminescence: ok so it would not be that easy to lets say give the GMs a new command that lists the names of the chars that have been online for more than 12 hours to check on?`

**Comment by o11c** [comment]
There are some ancient forum threads discussing vague possibilities.
