### ISSUE TITLE
Trying to Change Characters errors M+

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#188]
Login, you have to wait until you can switch characters first.
Then just try to use M+ to switch to a different character.
M+ errors.

**Comment by wushin** [comment]
Login, you have to wait until you can switch characters first.
Then just try to use M+ to switch to a different character.
M+ errors.

**Comment by mekolat** [comment]
that's not a bug, it's `prevent_logout` from battle_conf. The main server has it set to 0 so you can always switch char but the test server, for some reason, seems to have it set to 1

**Comment by mekolat** [comment]
@wushin close this?
