### ISSUE TITLE
Make all items stackable

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#191]

**Comment by mekolat** [comment]
proposal: add a new `stack` column in item db
```yaml
1: the item stacks up to 1 (does not stack)
ℕ: the item stacks up to ℕ or up to MAX set in conf if ℕ > MAX
0: the item stacks up to MAX
```

**Comment by wushin** [comment]
So you want to keep the stack/notstack but remove them from TMW

**Comment by mekolat** [comment]
exactly, so forks can use stack if they want as TMWA is an engine

**Comment by mekolat** [comment]
also I would make some very bulky items not stack (ie: luggage, iten) or stack up to 5

**Comment by wushin** [comment]
ok, that what I thought. Works for me.

**Comment by mekolat** [comment]
We will have to check what happens when a *stacked* item is equiped, maybe it would cause some weird behaviour with `getitem`, `delitem` or `undress`
