### ISSUE TITLE
[DIS] make it impossible to sit on GMs, or harder

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#221]
```
[22:50] Prsm: i am not a fan of doomspot
[22:50] Prsm: i would rather have something that makes them so they cant sit on me
[22:50] Prsm: would make life easier, and less conflict
```

I see 2 solutions:
- While GMs are sitting, make it impossible for players to pass over the tile
  - Requires implementing the set tile packet
  - If the player is using a newer client, send a set tile packet to tell them there is collision on this tile
  - If the player is using an older client, we can't send the set tile packet, but we can knock back the player one tile when they walk on the gm

-or-
- While GMs are sitting, if a player stands on their tile for more than 3 seconds, move them to an adjacent tile

@wushin suggestions?

**Comment by wushin** [comment]
// gat系
/*==========================================
 * (m,x,y)の状態を調べる
 *------------------------------------------
 */
MapCell map_getcell(Borrowed<map_local> m, int x, int y)
{
    if (x < 0 || x >= m->xs - 1 || y < 0 || y >= m->ys - 1)
        return MapCell::UNWALKABLE;
    return m->gat[x + y * m->xs];
}

/*==========================================
 * (m,x,y)の状態をtにする
 *------------------------------------------
 */
void map_setcell(Borrowed<map_local> m, int x, int y, MapCell t)
{
    if (x < 0 || x >= m->xs || y < 0 || y >= m->ys)
        return;
    m->gat[x + y * m->xs] = t;
}

**Comment by mekolat** [comment]
@wushin yes, we can easily `setcell` server-side BUT we need a way to send the updated collision to the clients with `SMSG_ADMIN_SET_TILE_TYPE`

**Comment by wushin** [comment]
Why do we need to send the updated collision to the client?

**Comment by mekolat** [comment]
@wushin so that the client will make you stop, as if you've hit a wall. But for old clients that don't have the packet implemented then we just knockback 1 tile when they attempt to walk on it
