### ISSUE TITLE
Casture the Ugly has anger problems

### ISSUE THREAD

**Issue by daniel-santos** [themanaworld/tmwa#37]
I've tried many combinations, but he always kills me when I try to turn in the bandana from the pirate cave. I have yet to actually *kill* a pirate (tried many times, died the sane number), so I hope that this isn't the cause, and if it is then the text should try to hit that is the reason he's so upset. I've even gone naked. I've never had another bandana other than the one from the chest in the bandit cave. I'm also suspecting the manaplus client since I built it from git.

**Comment by mekolat** [comment]
First of all, it can't be any bandana, it needs to be the one you found in the chest in the pirate cave. If you just give any bandana without opening the chest he kills you.

If you opened the chest talk to him and do "Yes, check this Bandana I brought."

**Comment by mekolat** [comment]
And by the way @daniel-santos please use the forums in the future to report bugs: https://forums.themanaworld.org/viewforum.php?f=3
