### ISSUE TITLE
Do not allow to escape a sub (or hop into without callsub)

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#80]
I want to make these changes but I don't know how:
- make `menu` only allow to use labels starting with `S_` when within a sub and only `L_` otherwise
- make `goto` only allow to use labels starting with `S_` when within a sub and only `L_` otherwise (and never `On` since this should be with donpcevent)

**Comment by mekolat** [comment]
@wushin why did you close this? it's not done

**Comment by wushin** [comment]
@mekolat I thought you did

**Comment by mekolat** [comment]
no, the reason I made an issue is because I have no clue how to do this
