### ISSUE TITLE
Debug atcommands

### ISSUE THREAD

**Issue by nashley** [themanaworld/tmwa#81]
It'd be nice if devs could list and edit quest variables with @ commands instead of making and then using using debug NPCs.
It could be as simple as a few commands: `@varlist <search>`, `@vartype variable`, and `@varedit variable value` for example.

**Comment by mekolat** [comment]
This could be baked into magic like the now-deleted "debug" quasi-spell but it would have to be cleaner and not a [pyramid of doom](http://survivejs.com/common_problems/pyramid.html). What I would do is add a new menu option to the `Debug` function (invoked with the `#debug` quasi-spell) that would invoke a new function, like `DebugQuests`.

**Comment by nashley** [comment]
@mekolat That's a good idea. The only issue is that you'd then have to scroll through quests & variables to find the one you're looking for. Perhaps both an addon to the #debug menu and atcommands could be implemented?

**Comment by mekolat** [comment]
@nashley not atcommands as we are planning to move those to magic as well

**Comment by mekolat** [comment]
and for having to scroll down the list we could solve that by making subcategories

**Comment by nashley** [comment]
@mekolat What will happen to GM commands then? Will they become spells?

**Comment by mekolat** [comment]
@nashley yep
