### ISSUE TITLE
better db backend

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#85]
the lighter the better as it's not storing an intense amount of data. It's more OLTP.

**Comment by nashley** [comment]
What about a different DB system? [Redis](http://redis.io/) looks interesting.

**Comment by wushin** [comment]
not opposed to any option so long as it's simple.

**Comment by mekolat** [comment]
Redis would be nice
also, https://github.com/google/leveldb and http://tarantool.org/
